spring.application.name=backend

spring.datasource.url=jdbc:postgresql://dpg-d2u5i3er433s73e08aa0-a.frankfurt-postgres.render.com/cook_note_7qx6
spring.datasource.username=user
spring.datasource.password=HquZmGX1pg1v8mUpvRAn4ie7AFuFQI2I
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true

file.upload-dir=uploads
